import "./globals.css";
import ProviderPage from "./Provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body className="">
<ProviderPage children={children}/>

  
    </body>
    </html>
  );
}
